site_name: MkLeung

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default
    
nav:
  - Home: 
    - index.md
    - 更新记录: update_logs.md
  - machine learning: 
    - ML/index.md
    - machine learning: ML/ml/ml.md
    - deep learning: ML/dl/dl.md 
  - others: 
    - others/index.md
    - 网站推荐: others/good_sites.md 
